[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200
upload_speed = 921600

board_upload.flash_size = 16MB
lib_deps =
    bodmer/TFT_eSPI @ ^2.5.43
    arduino-libraries/NTPClient @ ^3.2.1